#CREATE DATABASE configpub;
USE configpub;

CREATE TABLE `ORGANIZATION` (
  `ID` binary(16) NOT NULL,
  `NAME` varchar(30) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `USER` (
  `ID` binary(16) NOT NULL,
  `USER` varchar(25) NOT NULL,
  `PASS` varchar(30) DEFAULT NULL,
  `SALT` varchar(15) DEFAULT NULL,
  `FIRST_NAME` varchar(25) DEFAULT NULL,
  `LAST_NAME` varchar(35) NOT NULL,
  `EMAIL` varchar(50) NOT NULL,
  `ORGANIZATION` binary(16) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `ORGANIZATION` (`ORGANIZATION`),
  CONSTRAINT `USER_ORGANIZATION_fk` FOREIGN KEY (`ORGANIZATION`) REFERENCES `ORGANIZATION` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `ARTIFACT` (
  `ID` binary(16) NOT NULL,
  `NAME` varchar(40) NOT NULL,
  `CREATOR` binary(16) NOT NULL,
  `ORGANIZATION` binary(16) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `ORGANIZATION` (`ORGANIZATION`),
  KEY `CREATOR` (`CREATOR`),
  CONSTRAINT `ARTIFACT_ORGANIZATION_fk` FOREIGN KEY (`ORGANIZATION`) REFERENCES `ORGANIZATION` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ARTIFACT_USER_fk` FOREIGN KEY (`CREATOR`) REFERENCES `USER` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `ENVIRONMENT` (
  `ID` binary(16) NOT NULL,
  `NAME` varchar(40) NOT NULL,
  `ARTIFACT` binary(16) NOT NULL,
  `CREATOR` binary(16) NOT NULL,
  `TYPE` tinyint(4) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `ARTIFACT` (`ARTIFACT`),
  KEY `CREATOR` (`CREATOR`),
  CONSTRAINT `ENVIRONMENT_ARTIFACT_fk` FOREIGN KEY (`ARTIFACT`) REFERENCES `ARTIFACT` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ENVIRONMENT_USER_fk` FOREIGN KEY (`CREATOR`) REFERENCES `USER` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `CONFIGURATION` (
  `ID` binary(16) NOT NULL,
  `PARENT` binary(16) DEFAULT NULL,
  `ENVIRONMENT` binary(16) DEFAULT NULL,
  `ARTIFACT` binary(16) DEFAULT NULL,
  `VERSION_MAJOR` smallint(6) NOT NULL,
  `VERSION_MINOR` smallint(6) NOT NULL,
  `VERSION_PATCH` smallint(6) NOT NULL,
  `VERSION_STAGE` varchar(25) NOT NULL,
  `VCS_TAG` varchar(30) DEFAULT NULL,
  `ALIAS` varchar(40) DEFAULT NULL,
  `NAME` varchar(40) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `ARTIFACT` (`ARTIFACT`),
  KEY `ENVIRONMENT` (`ENVIRONMENT`),
  KEY `PARENT` (`PARENT`),
  CONSTRAINT `CONFIGURATION_ARTIFACT_fk` FOREIGN KEY (`ARTIFACT`) REFERENCES `ARTIFACT` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `CONFIGURATION_ENVIRONMENT_fk` FOREIGN KEY (`ENVIRONMENT`) REFERENCES `ENVIRONMENT` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `CONFIGURATION_CONFIGURATION_fk` FOREIGN KEY (`PARENT`) REFERENCES `CONFIGURATION` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `CONFIGURATION_ITEM` (
  `ID` binary(16) NOT NULL,
  `CONFIGURATION` binary(16) NOT NULL,
  `K` varchar(255) NOT NULL,
  `V` varchar(255) NOT NULL,
  `TYPE` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CONFIGURATION` (`CONFIGURATION`),
  CONSTRAINT `CONFIGURATION_ITEM_CONFIGURATION_fk` FOREIGN KEY (`CONFIGURATION`) REFERENCES `CONFIGURATION` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE CONFIGURATION_ITEM_COMMENT
(
  ID BINARY(16) PRIMARY KEY NOT NULL,
  CONFIGURATION_ITEM BINARY(16) NOT NULL,
  COMMENT TEXT NOT NULL,
  KEY `CONFIGURATION_ITEM` (`CONFIGURATION_ITEM`),
  CONSTRAINT `CONFIGURATION_ITEM_COMMENT_CONFIGURATION_ITEM_fk` FOREIGN KEY (`CONFIGURATION_ITEM`) REFERENCES `CONFIGURATION_ITEM` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ALTER TABLE configpub.CONFIGURATION_ITEM_COMMENT ADD CONSTRAINT unique_CONFIGURATION_ITEM UNIQUE (CONFIGURATION_ITEM);

CREATE FUNCTION `toUuid`($data BINARY(16)) RETURNS char(36) CHARSET utf8
DETERMINISTIC
NO SQL
  BEGIN
    DECLARE $result CHAR(36) DEFAULT NULL;
    IF $data IS NOT NULL THEN
      SET $result =
      CONCAT(
          HEX(SUBSTRING($data,5,4)), '-', HEX(SUBSTRING($data,3,2)), '-',
          HEX(SUBSTRING($data,1,2)), '-', HEX(SUBSTRING($data,9,2)), '-',
          HEX(SUBSTRING($data,11,6)));
    END IF;
    RETURN $result;
  END;

CREATE FUNCTION `toBin`($data VARCHAR(36)) RETURNS BINARY(16)
DETERMINISTIC
NO SQL
  BEGIN
    DECLARE $result BINARY(16) DEFAULT NULL;
    IF $data IS NOT NULL THEN
      SET $data = REPLACE($data,'-','');
      SET $result =
      CONCAT(UNHEX(SUBSTRING($data,13,4)), UNHEX(SUBSTRING($data,9,4)),
             UNHEX(SUBSTRING($data,1,8)), UNHEX(SUBSTRING($data,17,16)));
    END IF;
    RETURN $result;
  END;

